#!/bin/bash
 
sxhkd &
picom --config $HOME/.config/picom/picom.conf &

feh -Z --bg-scale /home/almondbubby/Documents/Wallpapers/your-name-sky-stars-kimi-no-na-wa-lights-anime-10260.png

killall -q polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar top &

xsetroot -cursor_name left_ptr

bspc config border_width	5
bspc config window_gap		10
 
bspc config split_ratio		0.62
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
 
bspc config automatic_scheme	spiral
 
bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on


bspc monitor HDMI-1-0 -d 1 2 3 4 5 6
bspc monitor eDP1 -d 7 8 9 0 11 12
