#!/bin/bash
 
sxhkd &
picom --config $HOME/.config/picom/picom.conf &

if [[ $(xrandr -q | grep 'HDMI-0 connected') ]]; then
	xrandr --output HDMI-0 --primary --mode 2560x1440 --rotate normal --output eDP-1-1 --mode 1920x1080 --rotate normal --right-of HDMI-0
fi

feh --bg-scale /home/almondbubby/Documents/Wallpapers/ddfb91cdcf5620c2bf554afb2202d2e9.png

killall -q polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

polybar top_external &

if [[ $(xrandr -q | grep 'HDMI-0 connected') ]]; then
	polybar top &
fi

xsetroot -cursor_name left_ptr

bspc config border_width	5
bspc config window_gap		10
 
bspc config split_ratio		0.62
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
 
bspc config automatic_scheme	spiral
 
bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on


bspc monitor HDMI-0 -d 1 2 3 4 5 6
bspc monitor eDP-1-1 -d 1 2 3 4 5 6
